/**
 * Top Navigation Configuration — GENERATED (nav-population-reliability-001).
 *
 * AUTO-GENERATED by the release pipeline from the (domain) route group's
 * top-level pages. DO NOT hand-edit — this file is regenerated on every
 * release. The substrate TopNav reads NAV_CONFIG.primary / NAV_CONFIG.groups.
 */

export type NavLink = {
  href: string;
  label: string;
  /** Operator/admin route — TopNav shows it only to admins. */
  adminOnly?: boolean;
};

export type NavGroup = {
  label: string;
  links: NavLink[];
};

export type NavConfig = {
  primary: NavLink[];
  groups: NavGroup[];
};

export const NAV_CONFIG: NavConfig = {
  primary: [
    { href: "/", label: "Home" },
    { href: "/campaigns", label: "Campaigns" },
    { href: "/meetings", label: "Meetings" },
    { href: "/pipeline", label: "Pipeline" },
    { href: "/prospects", label: "Prospects" },
    { href: "/replies", label: "Replies" },
    { href: "/suppressions", label: "Suppressions" },
  ],
  groups: [],
};
